# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

homeassistant:
  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 10.0.1.0/24
        - 172.17.0.0/16

panel_custom:
  - name: floorplan
    sidebar_title: Floorplan
    sidebar_icon: mdi:home
    url_path: floorplan
    config: !include floorplan.yaml
    
sensor:
  - platform: steam_online
    api_key: API_KEY
    accounts: 
      - 76561198054954663
      - 76561198186678119
  - platform: gtfs
    data: mta-subway.zip
    origin: 235
    destination: 632
  
  # Commute for Z  
  - platform: google_travel_time
    name: Work Commute for Z
    api_key: API_KEY
    origin: zone.home
    destination: Z-Work
    scan_interval: 600
    options:
      mode: transit
  # Commute for N
  - platform: google_travel_time
    name: Work Commute for N
    api_key: API_KEY
    origin: zone.home  
    destination: N-Work
    scan_interval: 600
    options:
      mode: transit

spotify:
  client_id: 7094906ff3694618b499d85a972b19a7
  client_secret: CLIENT_SECRET

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

